# Generated by Django 4.2.7 on 2023-11-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=150)),
                ('order_time', models.DateTimeField()),
            ],
        ),
    ]
